version: '3'
services:
  node_app:
    image: mongo
    ports:
      - "8800:8800"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/video-streaming-db

  # MongoDB
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
